-- Paginated report dataset query for Job + related Customer and Contact
-- Parameter: @JobID (nvarchar(6))
-- All fields translated to English names for better readability

SELECT
	-- Job Fields (order___ table)
	[Job].ord__ref AS [Job ID],
	[Job].ord__rpn AS [Job keyword],
	[Job].jobnr_vw AS [Process ID],
	[Job].best_dat AS [Order date],
	[Job].kla__ref AS [Job Customer ID],
	[Job].kla__rpn AS [Job Customer keyword],
	[Job].klgr_ref AS [Job Customer group ID],
	[Job].knp__ref AS [Job Contact ID],
	[Job].vrt__ref AS [Job Representative ID],
	[Job].kommiss_ AS [Job Commission agent],
	[Job].lev__ref AS [Job External commission agent],
	[Job].kommiss2 AS [External commission],
	[Job].ktrk_ref AS [Project ID],
	[Job].prd__ref AS [Product type ID],
	[Job].kpn__srt AS [Kind of work],
	[Job].afw__srt AS [Finishing type],
	[Job].type_ord AS [Job type],
	[Job].prkl_ref AS [Product group ID],
	[Job].ean___nr AS [EAN number],
	[Job].omschr__ AS [Description],
	[Job].gesl_bre AS [Finished size width],
	[Job].gesl_len AS [Finished size height],
	[Job].rug_____ AS [Backing],
	[Job].vouw____ AS [Fold],
	[Job].vouw___2 AS [Fold 2],
	[Job].open_bre AS [Flat size width],
	[Job].open_len AS [Flat size height],
	[Job].oplage__ AS [Quantity],
	[Job].vglopl__ AS [Comparison quantity],
	[Job].wpafwref AS [Cost center ID finishing machine],
	[Job].plts_kod AS [Delivery code],
	[Job].lok__ref AS [Delivery address ID],
	[Job].knplkref AS [Job Delivery Contact ID],
	[Job].trn__ref AS [Transport zone ID],
	[Job].trnt_ref AS [Transport rate ID],
	[Job].leverdat AS [Delivery date],
	[Job].leveruur AS [Delivery time],
	[Job].leverkod AS [Delivery urgency],
	[Job].leverkom AS [Delivery comment],
	[Job].fsc__ref AS [Certificate ID],
	[Job].bsbn_kla AS [Customer ID/order no.],
	[Job].lotnrkla AS [Batch ID],
	[Job].refbykla AS [Ref. at customer],
	[Job].flms_ref AS [Film reference],
	[Job].edi__idf AS [EDI identifier],
	[Job].spec_lev AS [Specification supplier],
	[Job].offa_ref AS [Article reference],
	[Job].bon__ref AS [Estimate ID],
	[Job].off__ref AS [Calculation ID],
	[Job].off__dat AS [Estimate date],
	[Job].vorigord AS [Previous job],
	[Job].voorz_bd AS [Expected amount],
	[Job].krit___1 AS [Criterion 01],
	[Job].krit___2 AS [Criterion 02],
	[Job].kom__ref AS [Comment ID],
	[Job].type_prd AS [Type of production],
	[Job].type__oa AS [Completely in Outside Services],
	[Job].klassemt AS [Classification],
	[Job].vrij_dat AS [Free date],
	[Job].goed_drk AS [Ready to print],
	[Job].goedudrk AS [Ready to print time],
	[Job].goed_afw AS [Ready for finishing],
	[Job].goeduafw AS [Ready for finishing time],
	[Job].goed_lev AS [Final production time],
	[Job].goedulev AS [Final production time hour],
	[Job].goed_lev_manueel AS [Final production time manual],
	[Job].plwy_ref AS [Planning way reference],
	[Job].pmd__ref AS [Scheduling model],
	[Job].pln_dt_0 AS [Lead time hours: order - proofs],
	[Job].pln_dt_1 AS [Lead time hours: proofs - start print],
	[Job].pln_dt_2 AS [Lead time hours: end print - finishing],
	[Job].pln_dt_3 AS [Lead time hours: end finishing - transport],
	[Job].pln_dd_0 AS [Lead time days: order date - proofs],
	[Job].pln_dd_1 AS [Lead time days: proofs - start print],
	[Job].pln_dd_2 AS [Lead time days: end print - finishing],
	[Job].pln_dd_3 AS [Lead time days: end finishing - transport],
	[Job].levertyd AS [No. of transport days],
	[Job].fiat_prd AS [Production approval],
	[Job].blok_atl AS [Blocked for clocking],
	[Job].bloktxt1 AS [Block text 1],
	[Job].bloktxt2 AS [Block text 2],
	[Job].blok_dat AS [Block date],
	[Job].blok_usr AS [Block user],
	[Job].bom___ok AS [Material list OK],
	[Job].bom__dat AS [Material list: adjustment date],
	[Job].bom__usr AS [Material list: adjustment user],
	[Job].bom__com AS [Material list: adjustment comment],
	[Job].boa___ok AS [BOM approval OK],
	[Job].boa__dat AS [BOM approval date],
	[Job].boa__usr AS [BOM approval user],
	[Job].boa__com AS [BOM approval comment],
	[Job].toe_tmp_ AS [Temporary addition],
	[Job].dat_tmp_ AS [Temporary date],
	[Job].afgewrkt AS [Worked off],
	[Job].prodwijz AS [Production change],
	[Job].bon__cnt AS [Estimate count],
	[Job].ord_begl AS [Job manager],
	[Job].kalkulat AS [Calculator],
	[Job].int_cont AS [Internal contact],
	[Job].faktur_1 AS [Invoice comment 01],
	[Job].faktur_2 AS [Invoice comment 02],
	[Job].oab__weg AS [Outside services path],
	[Job].grdb_weg AS [Material path],
	[Job].stbw_weg AS [Stock path],
	[Job].pntn_weg AS [Clockings path],
	[Job].pdkn_weg AS [Packaging path],
	[Job].plan_weg AS [Planning path],
	[Job].matb_weg AS [Material booking path],
	[Job].levb_weg AS [Delivery booking path],
	[Job].ofk__weg AS [Estimate path],
	[Job].res__weg AS [Reservation path],
	[Job].hfl__weg AS [Half path],
	[Job].wkb__weg AS [Work path],
	[Job].groepeer AS [Grouping order],
	[Job].munt_ref AS [Currency ID],
	[Job].aant_dec AS [No. of decimals],
	[Job].koers___ AS [Rate of exchange],
	[Job].prys_srt AS [Price type],
	[Job].oplag_vm AS [Quantity VM],
	[Job].oplag_bm AS [Quantity BM],
	[Job].oplag_om AS [Quantity OM],
	[Job].extra_vm AS [Extra VM],
	[Job].extra_bm AS [Extra BM],
	[Job].extra_om AS [Extra OM],
	[Job].btw_____ AS [VAT],
	[Job].arek_ref AS [Account ID],
	[Job].wp___ref AS [Cost center ID],
	[Job].ksrt_ref AS [Cost category ID],
	[Job].omsaant_ AS [Description count],
	[Job].dgbk_ref AS [Journal ID],
	[Job].dossier_ AS [Dossier],
	[Job].oplagtxt AS [Quantity description],
	[Job].extratxt AS [Extra text],
	[Job].fkla_ref AS [Invoice customer],
	[Job].fknp_ref AS [Invoice customer contact],
	[Job].fmd__ref AS [Invoice model],
	[Job].fac__typ AS [Invoice type],
	[Job].fac__wyz AS [Invoice mode],
	[Job].n1______ AS [Custom field 01],
	[Job].n2______ AS [Custom field 02],
	[Job].n3______ AS [Custom field 03],
	[Job].n4______ AS [Custom field 04],
	[Job].n5______ AS [Custom field 05],
	[Job].n6______ AS [Custom field 06],
	[Job].n7______ AS [Custom field 07],
	[Job].n8______ AS [Custom field 08],
	[Job].n9______ AS [Custom field 09],
	[Job].n10_____ AS [Custom field 10],
	[Job].n11_____ AS [Custom field 11],
	[Job].n12_____ AS [Custom field 12],
	[Job].n13_____ AS [Custom field 13],
	[Job].n14_____ AS [Custom field 14],
	[Job].n15_____ AS [Custom field 15],
	[Job].n16_____ AS [Custom field 16],
	[Job].dat01___ AS [Free date field 01],
	[Job].dat02___ AS [Free date field 02],
	[Job].dat03___ AS [Free date field 03],
	[Job].dat04___ AS [Free date field 04],
	[Job].dat05___ AS [Free date field 05],
	[Job].open____ AS [Not out of WIP],
	[Job].dat_open AS [Out of WIP date],
	[Job].annul___ AS [Order cancelled],
	[Job].datannul AS [Cancellation date],
	[Job].jobnrher AS [Heritage job number],
	[Job].jobnrvdl AS [Delivery job number],
	[Job].fin___ok AS [Financial status],
	[Job].fin__com AS [Financial comment],
	[Job].fin__dat AS [Financial date],
	[Job].fin__usr AS [Financial user],
	[Job].kred_dat AS [Launch credit calculation],
	[Job].opvolgen AS [Follow up],
	[Job].cde___ap AS [Other software ID],
	[Job].tstval01 AS [Status 01],
	[Job].tstval02 AS [Status 02],
	[Job].tstval03 AS [Status 03],
	[Job].tstval04 AS [Status 04],
	[Job].tstval05 AS [Status 05],
	[Job].tstval06 AS [Status 06],
	[Job].tstval07 AS [Status 07],
	[Job].tstval08 AS [Status 08],
	[Job].tstval09 AS [Status 09],
	[Job].tstval10 AS [Status 10],
	[Job].tstval11 AS [Status 11],
	[Job].tstval12 AS [Status 12],
	[Job].tstval13 AS [Status 13],
	[Job].tstval14 AS [Status 14],
	[Job].tstval15 AS [Status 15],
	[Job].tstval16 AS [Status 16],
	[Job].tstval17 AS [Status 17],
	[Job].tstval18 AS [Status 18],
	[Job].tstval19 AS [Status 19],
	[Job].tstval20 AS [Status 20],
	[Job].vraag_01 AS [Extra question 01],
	[Job].vraag_02 AS [Extra question 02],
	[Job].vraag_03 AS [Extra question 03],
	[Job].vraag_04 AS [Extra question 04],
	[Job].vraag_05 AS [Extra question 05],
	[Job].vraag_06 AS [Extra question 06],
	[Job].vraag_07 AS [Extra question 07],
	[Job].vraag_08 AS [Extra question 08],
	[Job].vraag_09 AS [Extra question 09],
	[Job].vraag_10 AS [Extra question 10],
	[Job].antw__01 AS [Answer 01],
	[Job].antw__02 AS [Answer 02],
	[Job].antw__03 AS [Answer 03],
	[Job].antw__04 AS [Answer 04],
	[Job].antw__05 AS [Answer 05],
	[Job].antw__06 AS [Answer 06],
	[Job].antw__07 AS [Answer 07],
	[Job].antw__08 AS [Answer 08],
	[Job].antw__09 AS [Answer 09],
	[Job].antw__10 AS [Answer 10],
	[Job].antw__11 AS [Answer 11],
	[Job].antw__12 AS [Answer 12],
	[Job].antw__13 AS [Answer 13],
	[Job].antw__14 AS [Answer 14],
	[Job].antw__15 AS [Answer 15],
	[Job].antw__16 AS [Answer 16],
	[Job].antw__17 AS [Answer 17],
	[Job].antw__18 AS [Answer 18],
	[Job].antw__19 AS [Answer 19],
	[Job].antw__20 AS [Answer 20],
	[Job].antw__21 AS [Answer 21],
	[Job].antw__22 AS [Answer 22],
	[Job].antw__23 AS [Answer 23],
	[Job].antw__24 AS [Answer 24],
	[Job].antw__25 AS [Answer 25],
	[Job].antw__26 AS [Answer 26],
	[Job].antw__27 AS [Answer 27],
	[Job].antw__28 AS [Answer 28],
	[Job].antw__29 AS [Answer 29],
	[Job].antw__30 AS [Answer 30],
	[Job].flok_ref AS [Invoice address ID],
	[Job].flknpref AS [Invoice address contact ID],

	-- Customer Fields (klabas__ table)
	[Customer].kla__ref AS [Customer ID],
	[Customer].uuid AS [Customer UUID],
	[Customer].gln_____ AS [Global location number],
	[Customer].ape___nr AS [Company classification],
	[Customer].naam____ AS [Name],
	[Customer].dienst__ AS [Department],
	[Customer].straat__ AS [Street],
	[Customer].wijk____ AS [District],
	[Customer].land_ref AS [Country],
	[Customer].county__ AS [County],
	[Customer].state___ AS [State],
	[Customer].post_ref AS [Postal code],
	[Customer].postnaam AS [City],
	[Customer].kla__rpn AS [Customer keyword],
	[Customer].telefoon AS [Phone],
	[Customer].telefax_ AS [Fax],
	[Customer].speedtel AS [Phone Short],
	[Customer].speedfax AS [Fax Short],
	[Customer].telex___ AS [E-mail],
	[Customer].taal_ref AS [Language],
	[Customer].kla__com AS [Customer Comment],
	[Customer].mailing_ AS [Include in mailing],
	[Customer].letop___ AS [Beware],
	[Customer].website_ AS [Website],
	[Customer].dos__ref AS [Site ID],
	[Customer].dgbk_ref AS [Customer Journal ID],
	[Customer].munt_ref AS [Customer Currency ID],
	[Customer].munt2ref AS [Equivalent currency code],
	[Customer].betk_ref AS [Term of payment ID],
	[Customer].betw_ref AS [Manner of payment ID],
	[Customer].centrref AS [Collective account],
	[Customer].btw_beh_ AS [VAT administration],
	[Customer].stx_beh_ AS [Sales tax administration],
	[Customer].btw___nr AS [VAT no.],
	[Customer].btw_____ AS [VAT],
	[Customer].land__nr AS [Country code VAT],
	[Customer].handelnm AS [Trading name],
	[Customer].handelnr AS [Trade no.],
	[Customer].bankrek_ AS [Bank account],
	[Customer].land_rek AS [Country code bank account],
	[Customer].iban____ AS [IBAN],
	[Customer].bic_____ AS [BIC/SWIFT],
	[Customer].fkt___ex AS [No. of invoices],
	[Customer].fkt_com1 AS [Invoice comment 1],
	[Customer].fkt_com2 AS [Invoice comment 2],
	[Customer].fkt_form AS [Invoice footer],
	[Customer].arek_ref AS [Account],
	[Customer].fkla_ref AS [Invoice customer],
	[Customer].fknp_ref AS [Invoice customer contact],
	[Customer].fkla2ref AS [Invoice customer supplementary costs],
	[Customer].fkla2typ AS [Invoice customer supplementary type],
	[Customer].fknp2ref AS [Invoice customer contact supplementary],
	[Customer].fstckcre AS [Stock order copy invoice lines],
	[Customer].fstcktst AS [Stock order invoice test version],
	[Customer].flok_ref AS [Invoice address ID],
	[Customer].fknp3ref AS [Invoice address contact ID],
	[Customer].grp__fac AS [Invoice grouping],
	[Customer].fmdporef AS [Production job invoice model],
	[Customer].fmdkoref AS [Sales order invoice model],
	[Customer].fac__typ AS [Invoice mode],
	[Customer].klgr_ref AS [Customer Group ID],
	[Customer].klsegref AS [Customer group 2],
	[Customer].vrzm_kla AS [Parent company ID],
	[Customer].kla_hvdt AS [Major grouping customer],
	[Customer].kla__vdt AS [Customer grouping],
	[Customer].beoordel AS [Rating],
	[Customer].status__ AS [Customer status],
	[Customer].stat_dat AS [Status date],
	[Customer].vrt__ref AS [Customer Representative ID],
	[Customer].kommiss_ AS [Commission internal representative],
	[Customer].lev__ref AS [Commissioner],
	[Customer].kommiss2 AS [External commission],
	[Customer].kom2_kom AS [External commission comment],
	[Customer].aanman__ AS [Send collection letters],
	[Customer].kort__af AS [Discount articles],
	[Customer].grp___af AS [Grouping articles invoices],
	[Customer].grp__2af AS [Extra costs grouping],
	[Customer].bkla_ref AS [Customer who pays],
	[Customer].kltlevnr AS [Our ID at customer],
	[Customer].dgprdfac AS [Invoice product term],
	[Customer].dgprddel AS [Destroy product term],
	[Customer].qalvlref AS [Quality level products],
	[Customer].smpl_typ AS [Sample plan ID],
	[Customer].smpl_str AS [Fixed amount copies per ribbon],
	[Customer].smpl_stp AS [Fixed step sample rolls],
	[Customer].smpl_ref AS [Reference sample table],
	[Customer].smpl_nul AS [No. of 0-samples],
	[Customer].smplvar1 AS [Extra variable sampling 1],
	[Customer].smplvar2 AS [Extra variable sampling 2],
	[Customer].smplvar3 AS [Extra variable sampling 3],
	[Customer].smplvar4 AS [Extra variable sampling 4],
	[Customer].vrz__num AS [Number insurance company],
	[Customer].vrz__tst AS [Request status],
	[Customer].amo__ask AS [Requested amount],
	[Customer].amo__akn AS [Total authorized amount],
	[Customer].amoaknvm AS [Authorized amount customer currency],
	[Customer].amoaknom AS [Authorized amount nominal],
	[Customer].vrzvvdat AS [Due date],
	[Customer].vrzbetko AS [Term of payment ID],
	[Customer].vrz__com AS [Customer Insurance Comment],
	[Customer].vrz_zone AS [Free fields selections],
	[Customer].vrz_mij_ AS [Insurance code],
	[Customer].grd_vrrd AS [Material stock],
	[Customer].vgo_vrrd AS [Product stock],
	[Customer].ngo_opbr AS [Not invoiced orders revenue],
	[Customer].ngo_kost AS [Not invoiced orders costs],
	[Customer].ngkoopbr AS [Not invoiced purchase revenue],
	[Customer].openstf_ AS [Open invoice amount],
	[Customer].ovschr_o AS [Overdue revenue],
	[Customer].ovschr_k AS [Overdue costs],
	[Customer].ngo_aant AS [Amount jobs to be invoiced],
	[Customer].ngkoaant AS [Amount sales orders to be invoiced],
	[Customer].opf_aant AS [No. of unpaid invoices],
	[Customer].oudstefk AS [Date oldest invoice],
	[Customer].volglev_ AS [Date next shipment],
	[Customer].le_berek AS [Date latest calculation],
	[Customer].lok__ref AS [Delivery address],
	[Customer].levtrref AS [Favourite transporter],
	[Customer].ltol_ref AS [Delivery allowance],
	[Customer].trn__ref AS [Transport zone],
	[Customer].trnt_ref AS [Transport favourite rate],
	[Customer].trncom_1 AS [Transport comment 1],
	[Customer].trncom_2 AS [Transport comment 2],
	[Customer].trncom_3 AS [Transport comment 3],
	[Customer].levvwref AS [Delivery conditions quote],
	[Customer].lvblay_p AS [Packing slip commercial PP],
	[Customer].lvblay_r AS [Packing slip rotation PP],
	[Customer].lvbpalnr AS [Packing slip pallet numbering],
	[Customer].lvbpalsm AS [Possible to compose pallets],
	[Customer].lvbompgr AS [Limit no more repacking],
	[Customer].pry__ref AS [Pricecode calculation],
	[Customer].ean___nr AS [EAN number EDI],
	[Customer].kol_trfp AS [Column tariff services],
	[Customer].geblokk_ AS [Blocked for jobs],
	[Customer].gblk_off AS [Locked for quotes],
	[Customer].gblk_fak AS [Locked for invoices],
	[Customer].gblk_lev AS [Locked for deliveries],
	[Customer].gblk_bst AS [Blocked for sales orders],
	[Customer].aanmaak_ AS [Creation date],
	[Customer].user____ AS [Created by],
	[Customer].zaknpref AS [Contact mailings],
	[Customer].boknpref AS [Contact invoices],
	[Customer].koknpref AS [Contact sales orders],
	[Customer].akknpref AS [Contact purchases],
	[Customer].mnknpref AS [Contact approving pageproof],
	[Customer].ficlaynr AS [Customer card],
	[Customer].ontlaynr AS [Internet confirmation receipt],
	[Customer].bstlaynr AS [Order form],
	[Customer].uitlaynr AS [Pick slip],
	[Customer].lvblaynr AS [Packing slip],
	[Customer].rmalaynr AS [RMA],
	[Customer].afrlaynr AS [Call-off contract],
	[Customer].etilaynr AS [Layout Packing labels],
	[Customer].af1laynr AS [Layout invoices customer orders],
	[Customer].ofblaynr AS [Layout Quote letter],
	[Customer].ofblulnr AS [Quote letter L&L],
	[Customer].artlaynr AS [Layout Standard calculation],
	[Customer].ordlaynr AS [Layout Order confirmation],
	[Customer].ordlulnr AS [Order confirmation L&L],
	[Customer].brflaynr AS [Message layout],
	[Customer].konlaynr AS [Project layout L&L],
	[Customer].edifalay AS [Export Sales invoices],
	[Customer].edifavlg AS [Export invoices Sequence no.],
	[Customer].fac__edi AS [Digital invoice no longer in use],
	[Customer].fac__pdf AS [Digital invoice PDF],
	[Customer].eml__bat AS [E-mail approval],
	[Customer].eml_bat3 AS [E-mail approval 3],
	[Customer].eml__vkp AS [E-mail sales order confirmation],
	[Customer].eml__trn AS [Transport e-mail],
	[Customer].cdeklaap AS [Customer Other software ID],
	[Customer].jobnr_vw AS [Customer Process ID],
	[Customer].pctnktoe AS [Percentage surcharge post-calculation],
	[Customer].mnt__ref AS [Default imposition procedure],
	[Customer].hit_dat1 AS [Date 1],
	[Customer].hit_dat2 AS [Date 2],
	[Customer].hit_dat3 AS [Date 3],
	[Customer].hit_str1 AS [String 1],
	[Customer].hit_str2 AS [String 2],
	[Customer].hit_str3 AS [String 3],
	[Customer].hit_get1 AS [Float 1],
	[Customer].hit_get2 AS [Float 2],
	[Customer].hit_get3 AS [Float 3],
	[Customer].vk_k_vst AS [Discount amount],
	[Customer].vk_k_pct AS [Discount percentage],
	[Customer].vk_kmpct AS [Commission percentage],
	[Customer].vk_kmkom AS [Commission comment],
	[Customer].vk_kfpct AS [Invoice discount percentage],
	[Customer].vk_tovst AS [Concession amount],
	[Customer].vk_topct AS [Concession percentage],
	[Customer].vk_betal AS [No. of days payment habit],
	[Customer].brf_prys AS [Price display type],
	[Customer].brf_supp AS [Surcharge display],
	[Customer].brf_oplv AS [Proposal quantity variations],
	[Customer].vkpan_pp AS [Sales price report with/without prepress],
	[Customer].eur__dat AS [When euro-conversion can be done],
	[Customer].ord_begl AS [Customer Job manager],
	[Customer].int_cont AS [Customer Internal contact],
	[Customer].bstrfweb AS [Ordering ID customers obligated],
	[Customer].faccmweb AS [Invoice comment obligated],
	[Customer].antw__01 AS [Answer 01],
	[Customer].antw__02 AS [Answer 02],
	[Customer].antw__03 AS [Answer 03],
	[Customer].antw__04 AS [Answer 04],
	[Customer].antw__05 AS [Answer 05],
	[Customer].antw__06 AS [Answer 06],
	[Customer].antw__07 AS [Answer 07],
	[Customer].antw__08 AS [Answer 08],
	[Customer].antw__09 AS [Answer 09],
	[Customer].antw__10 AS [Answer 10],
	[Customer].antw__11 AS [Answer 11],
	[Customer].antw__12 AS [Answer 12],
	[Customer].antw__13 AS [Answer 13],
	[Customer].antw__14 AS [Answer 14],
	[Customer].antw__15 AS [Answer 15],
	[Customer].antw__16 AS [Answer 16],
	[Customer].antw__17 AS [Answer 17],
	[Customer].antw__18 AS [Answer 18],
	[Customer].antw__19 AS [Answer 19],
	[Customer].antw__20 AS [Answer 20],
	[Customer].antw__21 AS [Answer 21],
	[Customer].antw__22 AS [Answer 22],
	[Customer].antw__23 AS [Answer 23],
	[Customer].antw__24 AS [Answer 24],
	[Customer].antw__25 AS [Answer 25],
	[Customer].antw__26 AS [Answer 26],
	[Customer].antw__27 AS [Answer 27],
	[Customer].antw__28 AS [Answer 28],
	[Customer].antw__29 AS [Answer 29],
	[Customer].antw__30 AS [Answer 30],
	[Customer].wij__dat AS [Latest change date],
	[Customer].wij__usr AS [User latest modification],
	[Customer].paswrdwb AS [Separate password net-applications],
	[Customer].w4lqqlog AS [Web4labels Quick Quote Logging],
	[Customer].w4lrfqem AS [Web4labels RFQ e-mail],
	[Customer].apv__src AS [Approvers from],
	[Customer].prijsweb AS [Show pricing on web],
	[Customer].tstval01 AS [Status 01],
	[Customer].tstval02 AS [Status 02],
	[Customer].tstval03 AS [Status 03],
	[Customer].tstval04 AS [Status 04],
	[Customer].tstval05 AS [Status 05],
	[Customer].tstval06 AS [Status 06],
	[Customer].tstval07 AS [Status 07],
	[Customer].tstval08 AS [Status 08],
	[Customer].tstval09 AS [Status 09],
	[Customer].tstval10 AS [Status 10],
	[Customer].rek_staf AS [Calculation method],
	[Customer].tariffs_default_number_of_months_valid AS [Tariff definitions validity period],
	[Customer].tariffs_fixed_end__dat AS [Tariff definitions end date fixed],
	[Customer].tariffs_fixed_vm AS [Tariff definitions for. cur. fixed],
	[Customer].tariffs_proposal_for_creation AS [Tariff definition proposal],
	[Customer].cerm8_record_version AS [Cerm8 Record Version],
	[Customer].lok_uuid AS [UUID of the address],
	[Customer].lok_cerm8_record_version AS [Cerm8 Record Version of the address],
	[Customer].rek_staf_src AS [Calculation manner],
	[Customer].vpakvast AS [Packing choice],

	-- Contact Fields (konpkl__ table)
	[Contact].kla__ref AS [Contact Customer ID],
	[Contact].uuid AS [Contact UUID],
	[Contact].knp__ref AS [Contact ID],
	[Contact].knp__nam AS [Contact name],
	[Contact].knp__vnm AS [Contact first name],
	[Contact].knp_lett AS [Initials],
	[Contact].knp__sex AS [Title],
	[Contact].straat_p AS [Street Home],
	[Contact].wijk___p AS [District Home],
	[Contact].landrefp AS [Country ID Home],
	[Contact].county_p AS [County Home],
	[Contact].state__p AS [State Home],
	[Contact].postrefp AS [Postal code Home],
	[Contact].postnamp AS [City Home],
	[Contact].tel__pkp AS [Phone Home],
	[Contact].sptelpkp AS [Speed dial phone Home],
	[Contact].fax__pkp AS [Fax Home],
	[Contact].spfaxpkp AS [Speed dial fax Home],
	[Contact].emailpkp AS [E-mail Home],
	[Contact].mailingp AS [Include in mailing Home],
	[Contact].straat__ AS [Street Work address],
	[Contact].wijk____ AS [District Work address],
	[Contact].land_ref AS [Country ID Work address],
	[Contact].county__ AS [County Work address],
	[Contact].state___ AS [State Work address],
	[Contact].post_ref AS [Postal code Work address],
	[Contact].postnaam AS [City Work address],
	[Contact].telefoon AS [Phone Work address],
	[Contact].speedtel AS [Speed dial phone Work address],
	[Contact].telefax_ AS [Fax Work address],
	[Contact].speedfax AS [Speed dial fax Work address],
	[Contact].email___ AS [E-mail Work address],
	[Contact].tel_auto AS [Mobile],
	[Contact].mailing_ AS [In mailing],
	[Contact].knpkr__1 AS [Criterion 01],
	[Contact].knpkr__2 AS [Criterion 02],
	[Contact].knpkr__3 AS [Criterion 03],
	[Contact].knpkr__4 AS [Criterion 04],
	[Contact].knpkr__5 AS [Criterion 05],
	[Contact].funktie_ AS [Function],
	[Contact].funk_int AS [Internal function],
	[Contact].taal_ref AS [Contact Language],
	[Contact].comment_ AS [Contact Comment],
	[Contact].in_gebr_ AS [Employed],
	[Contact].sender__ AS [Can this contact send files],
	[Contact].approver AS [Can this contact approve pages/proofs],
	[Contact].werkadrs AS [Work address],
	[Contact].voorvg_1 AS [Prefix 1],
	[Contact].voorvg_2 AS [Prefix 2],
	[Contact].achtvg__ AS [Suffix],
	[Contact].dienst_1 AS [Department 1],
	[Contact].dienst_2 AS [Department 2],
	[Contact].dienst_3 AS [Department 3],
	[Contact].knp_nam2 AS [Surname 2],
	[Contact].cdeklaap AS [Other software ID customer],
	[Contact].cde__aap AS [Other software ID application],
	[Contact].jobnr_vw AS [Contact Process ID],
	[Contact].web_bvst AS [Internet orders confirmation],
	[Contact].ofblaynr AS [Layout Quote letter],
	[Contact].ofblulnr AS [Quote letter L&L],
	[Contact].artlaynr AS [Layout Standard calculation],
	[Contact].ordlaynr AS [Layout Order confirmation],
	[Contact].ordlulnr AS [Order confirmation L&L],
	[Contact].brflaynr AS [Layout Message],
	[Contact].ontlaynr AS [Internet confirmation receipt],
	[Contact].bstlaynr AS [Order form],
	[Contact].rmalaynr AS [RMA],
	[Contact].afrlaynr AS [Call-off contracts],
	[Contact].af1laynr AS [Layout Invoice],
	[Contact].etilaynr AS [Layout Packing labels],
	[Contact].konlaynr AS [Layout Project L&L],
	[Contact].linkedin AS [LinkedIn],
	[Contact].facebook AS [Facebook],
	[Contact].twitter_ AS [Twitter],
	[Contact].datum___ AS [Date of birth],
	[Contact].antw__01 AS [Answer 01],
	[Contact].antw__02 AS [Answer 02],
	[Contact].antw__03 AS [Answer 03],
	[Contact].antw__04 AS [Answer 04],
	[Contact].antw__05 AS [Answer 05],
	[Contact].antw__06 AS [Answer 06],
	[Contact].antw__07 AS [Answer 07],
	[Contact].antw__08 AS [Answer 08],
	[Contact].antw__09 AS [Answer 09],
	[Contact].antw__10 AS [Answer 10],
	[Contact].antw__11 AS [Answer 11],
	[Contact].antw__12 AS [Answer 12],
	[Contact].antw__13 AS [Answer 13],
	[Contact].antw__14 AS [Answer 14],
	[Contact].antw__15 AS [Answer 15],
	[Contact].antw__16 AS [Answer 16],
	[Contact].antw__17 AS [Answer 17],
	[Contact].antw__18 AS [Answer 18],
	[Contact].antw__19 AS [Answer 19],
	[Contact].antw__20 AS [Answer 20],
	[Contact].antw__21 AS [Answer 21],
	[Contact].antw__22 AS [Answer 22],
	[Contact].antw__23 AS [Answer 23],
	[Contact].antw__24 AS [Answer 24],
	[Contact].antw__25 AS [Answer 25],
	[Contact].antw__26 AS [Answer 26],
	[Contact].antw__27 AS [Answer 27],
	[Contact].antw__28 AS [Answer 28],
	[Contact].antw__29 AS [Answer 29],
	[Contact].antw__30 AS [Answer 30],
	[Contact].aanmaak_ AS [Creation date],
	[Contact].wij__dat AS [Latest change date],
	[Contact].user____ AS [Created by],
	[Contact].wij__usr AS [User latest modification],
	[Contact].fac__eml AS [Digital invoices PDF],
	[Contact].fac2_eml AS [Digital invoices EDI export],
	[Contact].cerm8_record_version AS [Cerm8 Record Version]

FROM dbo.order___ AS [Job]
LEFT JOIN dbo.klabas__ AS [Customer]
	ON [Customer].kla__ref = [Job].kla__ref
LEFT JOIN dbo.konpkl__ AS [Contact]
	ON [Contact].kla__ref = [Job].kla__ref
	AND [Contact].knp__ref = [Job].knp__ref
WHERE [Job].ord__ref = @JobID;
