-- Paginated report dataset query for Job table only
-- Parameter: @JobID (nvarchar(6))
-- All fields translated to English names for better readability

SELECT
	ord__ref AS [Job ID],
	ord__rpn AS [Job keyword],
	jobnr_vw AS [Process ID],
	best_dat AS [Order date],
	kla__ref AS [Customer ID],
	kla__rpn AS [Customer keyword],
	klgr_ref AS [Customer group ID (Lijsten)],
	knp__ref AS [Contact ID],
	vrt__ref AS [Representative ID],
	kommiss_ AS [Commission agent],
	lev__ref AS [Commission agent 2],
	kommiss2 AS [External commission],
	ktrk_ref AS [Project ID],
	prd__ref AS [Product type ID],
	kpn__srt AS [Kind of work],
	afw__srt AS [Finishing type],
	type_ord AS [Job type],
	prkl_ref AS [Product group ID],
	ean___nr AS [EAN number],
	omschr__ AS [Description],
	gesl_bre AS [Finished size width],
	gesl_len AS [Finished size height],
	rug_____ AS [Backing],
	vouw____ AS [Fold 1],
	vouw___2 AS [Fold 2],
	open_bre AS [Flat size width],
	open_len AS [Flat size height],
	oplage__ AS [Quantity],
	vglopl__ AS [Comparison quantity],
	wpafwref AS [Cost center ID finishing machine],
	plts_kod AS [Delivery code],
	lok__ref AS [Delivery address ID],
	knplkref AS [Contact ID 2],
	trn__ref AS [Transport zone ID],
	trnt_ref AS [Transport rate ID],
	leverdat AS [Delivery date],
	leveruur AS [Delivery time],
	leverkod AS [Delivery urgency],
	leverkom AS [Delivery comment],
	fsc__ref AS [Certificate ID],
	bsbn_kla AS [Customer ID/order no.],
	lotnrkla AS [Batch ID],
	refbykla AS [Ref. at customer],
	flms_ref AS [Film reference],
	edi__idf AS [EDI identifier],
	spec_lev AS [Specification supplier],
	offa_ref AS [Article reference],
	bon__ref AS [Estimate ID],
	off__ref AS [Calculation ID],
	off__dat AS [Estimate date],
	vorigord AS [Previous job],
	voorz_bd AS [Expected amount],
	krit___1 AS [Criterion 01],
	krit___2 AS [Criterion 02],
	kom__ref AS [Comment ID],
	type_prd AS [Type of production],
	type__oa AS [Completely in Outside Services],
	klassemt AS [Classification],
	vrij_dat AS [Free date],
	goed_drk AS [Ready to print],
	goedudrk AS [Ready to print time],
	goed_afw AS [Ready for finishing],
	goeduafw AS [Ready for finishing time],
	goed_lev AS [Final production time],
	goedulev AS [Final production time hour],
	goed_lev_manueel AS [Final production time manual],
	plwy_ref AS [Planning way reference],
	pmd__ref AS [Scheduling model],
	pln_dt_0 AS [Lead time hours: order - proofs],
	pln_dt_1 AS [Lead time hours: proofs - start print],
	pln_dt_2 AS [Lead time hours: end print - finishing],
	pln_dt_3 AS [Lead time hours: end finishing - transport],
	pln_dd_0 AS [Lead time days: order date - proofs],
	pln_dd_1 AS [Lead time days: proofs - start print],
	pln_dd_2 AS [Lead time days: end print - finishing],
	pln_dd_3 AS [Lead time days: end finishing - transport],
	levertyd AS [No. of transport days],
	fiat_prd AS [Production approval],
	blok_atl AS [Blocked for clocking],
	bloktxt1 AS [Block text 1],
	bloktxt2 AS [Block text 2],
	blok_dat AS [Block date],
	blok_usr AS [Block user],
	bom___ok AS [Material list OK],
	bom__dat AS [Material list: adjustment date],
	bom__usr AS [Material list: adjustment user],
	bom__com AS [Material list: adjustment comment],
	boa___ok AS [BOM approval OK],
	boa__dat AS [BOM approval date],
	boa__usr AS [BOM approval user],
	boa__com AS [BOM approval comment],
	toe_tmp_ AS [Temporary addition],
	dat_tmp_ AS [Temporary date],
	afgewrkt AS [Worked off],
	prodwijz AS [Production change],
	bon__cnt AS [Estimate count],
	ord_begl AS [Job manager],
	kalkulat AS [Calculator],
	int_cont AS [Internal contact],
	faktur_1 AS [Invoice comment 01],
	faktur_2 AS [Invoice comment 02],
	oab__weg AS [Outside services path],
	grdb_weg AS [Material path],
	stbw_weg AS [Stock path],
	pntn_weg AS [Clockings path],
	pdkn_weg AS [Packaging path],
	plan_weg AS [Planning path],
	matb_weg AS [Material booking path],
	levb_weg AS [Delivery booking path],
	ofk__weg AS [Estimate path],
	res__weg AS [Reservation path],
	hfl__weg AS [Half path],
	wkb__weg AS [Work path],
	groepeer AS [Grouping order],
	munt_ref AS [Currency ID],
	aant_dec AS [No. of decimals],
	koers___ AS [Rate of exchange],
	prys_srt AS [Price type],
	oplag_vm AS [Quantity VM],
	oplag_bm AS [Quantity BM],
	oplag_om AS [Quantity OM],
	extra_vm AS [Extra VM],
	extra_bm AS [Extra BM],
	extra_om AS [Extra OM],
	btw_____ AS [VAT],
	arek_ref AS [Account ID],
	wp___ref AS [Cost center ID],
	ksrt_ref AS [Cost category ID],
	omsaant_ AS [Description count],
	dgbk_ref AS [Journal ID],
	dossier_ AS [Dossier],
	oplagtxt AS [Quantity description],
	extratxt AS [Extra text],
	fkla_ref AS [Invoice customer],
	fknp_ref AS [Invoice customer contact],
	fmd__ref AS [Invoice model],
	fac__typ AS [Invoice type],
	fac__wyz AS [Invoice mode],

	flok_ref AS [Invoice address ID],
	flknpref AS [Invoice address contact ID]
FROM dbo.order___
WHERE ord__ref = @JobID;
